version: '3.8'

services:
  minio:
    image: 'minio/minio:RELEASE.2024-03-05T04-48-44Z-cpuv1'
    container_name: ${COMPOSE_PROJECT_NAME}_minio
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${DC_MINIO_S3_PORT:-9000}:9000' # S3 API port
      - '${DC_MINIO_CONSOLE_PORT:-9001}:9001' # http Console port
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
    healthcheck:
     test: [ "CMD", "mc", "ready", "local" ]
     interval: 20s
     timeout: 5s
     retries: 3
    environment:
      MINIO_ROOT_USER: '${DC_MINIO_ROOT_USER:-manager}'
      MINIO_ROOT_PASSWORD: '${DC_MINIO_ROOT_PASS:-ChangeMe}'
